package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Control generated by hbm2java
 */
@Entity
@Table(name = "control", catalog = "hayturno")
public class Control implements java.io.Serializable {

	private ControlId id;
	private Persona persona;

	public Control() {
	}

	public Control(ControlId id, Persona persona) {
		this.id = id;
		this.persona = persona;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fecha", column = @Column(name = "fecha", length = 10)),
			@AttributeOverride(name = "peso", column = @Column(name = "peso", precision = 12, scale = 0)),
			@AttributeOverride(name = "imc", column = @Column(name = "imc", precision = 12, scale = 0)),
			@AttributeOverride(name = "observacion", column = @Column(name = "observacion", length = 200)),
			@AttributeOverride(name = "talla", column = @Column(name = "talla", length = 20)),
			@AttributeOverride(name = "idpersona", column = @Column(name = "idpersona", nullable = false)) })
	public ControlId getId() {
		return this.id;
	}

	public void setId(ControlId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false, insertable = false, updatable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

}
