package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Especialidad generated by hbm2java
 */
@Entity
@Table(name = "especialidad", catalog = "hayturno")
public class Especialidad implements java.io.Serializable {

	private Integer idespecialidad;
	private String especialidad;
	private Set<Doctor> doctors = new HashSet<Doctor>(0);

	public Especialidad() {
	}

	public Especialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public Especialidad(String especialidad, Set<Doctor> doctors) {
		this.especialidad = especialidad;
		this.doctors = doctors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idespecialidad", unique = true, nullable = false)
	public Integer getIdespecialidad() {
		return this.idespecialidad;
	}

	public void setIdespecialidad(Integer idespecialidad) {
		this.idespecialidad = idespecialidad;
	}

	@Column(name = "especialidad", nullable = false, length = 100)
	public String getEspecialidad() {
		return this.especialidad;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidad")
	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

}
