package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Obrasocial generated by hbm2java
 */
@Entity
@Table(name = "obrasocial", catalog = "hayturno")
public class Obrasocial implements java.io.Serializable {

	private Integer idobrasocial;
	private String obrasocial;
	private Boolean conConvenio;
	private String observaciones;
	private Set<ObrasocialPersona> obrasocialPersonas = new HashSet<ObrasocialPersona>(
			0);

	public Obrasocial() {
	}

	public Obrasocial(String obrasocial) {
		this.obrasocial = obrasocial;
	}

	public Obrasocial(String obrasocial, Boolean conConvenio,
			String observaciones, Set<ObrasocialPersona> obrasocialPersonas) {
		this.obrasocial = obrasocial;
		this.conConvenio = conConvenio;
		this.observaciones = observaciones;
		this.obrasocialPersonas = obrasocialPersonas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idobrasocial", unique = true, nullable = false)
	public Integer getIdobrasocial() {
		return this.idobrasocial;
	}

	public void setIdobrasocial(Integer idobrasocial) {
		this.idobrasocial = idobrasocial;
	}

	@Column(name = "obrasocial", nullable = false, length = 100)
	public String getObrasocial() {
		return this.obrasocial;
	}

	public void setObrasocial(String obrasocial) {
		this.obrasocial = obrasocial;
	}

	@Column(name = "con_convenio")
	public Boolean getConConvenio() {
		return this.conConvenio;
	}

	public void setConConvenio(Boolean conConvenio) {
		this.conConvenio = conConvenio;
	}

	@Column(name = "observaciones", length = 200)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "obrasocial")
	public Set<ObrasocialPersona> getObrasocialPersonas() {
		return this.obrasocialPersonas;
	}

	public void setObrasocialPersonas(Set<ObrasocialPersona> obrasocialPersonas) {
		this.obrasocialPersonas = obrasocialPersonas;
	}

}
