package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", catalog = "hayturno")
public class Persona implements java.io.Serializable {

	private Integer idpersona;
	private Localidad localidad;
	private Estado estado;
	private Provincia provincia;
	private Integer dni;
	private String nombre;
	private String apellido;
	private Date fechaNacimiento;
	private String barrio;
	private String telefono;
	private String celular;
	private String email;
	private Integer consultasDisponibles;
	private Float pesoInicial;
	private Float pesoSaludable;
	private Integer pesoPorcentajeObjetivo;
	private String observaciones;
	private Date fechaVencimientoPlan;
	private Set<Doctor> doctors = new HashSet<Doctor>(0);
	private Set<PersonaRol> personaRols = new HashSet<PersonaRol>(0);
	private Set<Turno> turnos = new HashSet<Turno>(0);
	private Set<ObrasocialPersona> obrasocialPersonas = new HashSet<ObrasocialPersona>(
			0);
	private Set<Control> controls = new HashSet<Control>(0);

	public Persona() {
	}

	public Persona(Localidad localidad, Estado estado, Provincia provincia,
			String email) {
		this.localidad = localidad;
		this.estado = estado;
		this.provincia = provincia;
		this.email = email;
	}

	public Persona(Localidad localidad, Estado estado, Provincia provincia,
			Integer dni, String nombre, String apellido, Date fechaNacimiento,
			String barrio, String telefono, String celular, String email,
			Integer consultasDisponibles, Float pesoInicial,
			Float pesoSaludable, Integer pesoPorcentajeObjetivo,
			String observaciones, Date fechaVencimientoPlan,
			Set<Doctor> doctors, Set<PersonaRol> personaRols,
			Set<Turno> turnos, Set<ObrasocialPersona> obrasocialPersonas,
			Set<Control> controls) {
		this.localidad = localidad;
		this.estado = estado;
		this.provincia = provincia;
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaNacimiento = fechaNacimiento;
		this.barrio = barrio;
		this.telefono = telefono;
		this.celular = celular;
		this.email = email;
		this.consultasDisponibles = consultasDisponibles;
		this.pesoInicial = pesoInicial;
		this.pesoSaludable = pesoSaludable;
		this.pesoPorcentajeObjetivo = pesoPorcentajeObjetivo;
		this.observaciones = observaciones;
		this.fechaVencimientoPlan = fechaVencimientoPlan;
		this.doctors = doctors;
		this.personaRols = personaRols;
		this.turnos = turnos;
		this.obrasocialPersonas = obrasocialPersonas;
		this.controls = controls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpersona", unique = true, nullable = false)
	public Integer getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(Integer idpersona) {
		this.idpersona = idpersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlocalidad", nullable = false)
	public Localidad getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprovincia", nullable = false)
	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Column(name = "dni")
	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	@Column(name = "nombre", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 100)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "barrio", length = 100)
	public String getBarrio() {
		return this.barrio;
	}

	public void setBarrio(String barrio) {
		this.barrio = barrio;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "celular", length = 20)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "consultas_disponibles")
	public Integer getConsultasDisponibles() {
		return this.consultasDisponibles;
	}

	public void setConsultasDisponibles(Integer consultasDisponibles) {
		this.consultasDisponibles = consultasDisponibles;
	}

	@Column(name = "peso_inicial", precision = 12, scale = 0)
	public Float getPesoInicial() {
		return this.pesoInicial;
	}

	public void setPesoInicial(Float pesoInicial) {
		this.pesoInicial = pesoInicial;
	}

	@Column(name = "peso_saludable", precision = 12, scale = 0)
	public Float getPesoSaludable() {
		return this.pesoSaludable;
	}

	public void setPesoSaludable(Float pesoSaludable) {
		this.pesoSaludable = pesoSaludable;
	}

	@Column(name = "peso_porcentaje_objetivo")
	public Integer getPesoPorcentajeObjetivo() {
		return this.pesoPorcentajeObjetivo;
	}

	public void setPesoPorcentajeObjetivo(Integer pesoPorcentajeObjetivo) {
		this.pesoPorcentajeObjetivo = pesoPorcentajeObjetivo;
	}

	@Column(name = "observaciones", length = 300)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_vencimiento_plan", length = 10)
	public Date getFechaVencimientoPlan() {
		return this.fechaVencimientoPlan;
	}

	public void setFechaVencimientoPlan(Date fechaVencimientoPlan) {
		this.fechaVencimientoPlan = fechaVencimientoPlan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<PersonaRol> getPersonaRols() {
		return this.personaRols;
	}

	public void setPersonaRols(Set<PersonaRol> personaRols) {
		this.personaRols = personaRols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Turno> getTurnos() {
		return this.turnos;
	}

	public void setTurnos(Set<Turno> turnos) {
		this.turnos = turnos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<ObrasocialPersona> getObrasocialPersonas() {
		return this.obrasocialPersonas;
	}

	public void setObrasocialPersonas(Set<ObrasocialPersona> obrasocialPersonas) {
		this.obrasocialPersonas = obrasocialPersonas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set<Control> getControls() {
		return this.controls;
	}

	public void setControls(Set<Control> controls) {
		this.controls = controls;
	}

}
