package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonaRol generated by hbm2java
 */
@Entity
@Table(name = "persona_rol", catalog = "hayturno")
public class PersonaRol implements java.io.Serializable {

	private Integer idpersonaRol;
	private Rol rol;
	private Persona persona;
	private String usuario;
	private String clave;

	public PersonaRol() {
	}

	public PersonaRol(Rol rol, Persona persona) {
		this.rol = rol;
		this.persona = persona;
	}

	public PersonaRol(Rol rol, Persona persona, String usuario, String clave) {
		this.rol = rol;
		this.persona = persona;
		this.usuario = usuario;
		this.clave = clave;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpersona_rol", unique = true, nullable = false)
	public Integer getIdpersonaRol() {
		return this.idpersonaRol;
	}

	public void setIdpersonaRol(Integer idpersonaRol) {
		this.idpersonaRol = idpersonaRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "usuario", length = 45)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", length = 45)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

}
