package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia", catalog = "hayturno")
public class Provincia implements java.io.Serializable {

	private Integer idprovincia;
	private String provincia;
	private Set<Localidad> localidads = new HashSet<Localidad>(0);
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Provincia() {
	}

	public Provincia(String provincia) {
		this.provincia = provincia;
	}

	public Provincia(String provincia, Set<Localidad> localidads,
			Set<Persona> personas) {
		this.provincia = provincia;
		this.localidads = localidads;
		this.personas = personas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idprovincia", unique = true, nullable = false)
	public Integer getIdprovincia() {
		return this.idprovincia;
	}

	public void setIdprovincia(Integer idprovincia) {
		this.idprovincia = idprovincia;
	}

	@Column(name = "provincia", nullable = false, length = 45)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<Localidad> getLocalidads() {
		return this.localidads;
	}

	public void setLocalidads(Set<Localidad> localidads) {
		this.localidads = localidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
