package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "hayturno")
public class Rol implements java.io.Serializable {

	private Integer idrol;
	private String rol;
	private Set<PersonaRol> personaRols = new HashSet<PersonaRol>(0);

	public Rol() {
	}

	public Rol(String rol) {
		this.rol = rol;
	}

	public Rol(String rol, Set<PersonaRol> personaRols) {
		this.rol = rol;
		this.personaRols = personaRols;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idrol", unique = true, nullable = false)
	public Integer getIdrol() {
		return this.idrol;
	}

	public void setIdrol(Integer idrol) {
		this.idrol = idrol;
	}

	@Column(name = "rol", nullable = false, length = 45)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<PersonaRol> getPersonaRols() {
		return this.personaRols;
	}

	public void setPersonaRols(Set<PersonaRol> personaRols) {
		this.personaRols = personaRols;
	}

}
