package com.hayturno.myapp.hibernatecode;

// Generated 15-ago-2015 21:00:45 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Turno generated by hbm2java
 */
@Entity
@Table(name = "turno", catalog = "hayturno")
public class Turno implements java.io.Serializable {

	private Integer idturno;
	private Doctor doctor;
	private Estado estado;
	private Persona persona;
	private Date fecha;
	private Date hora;
	private boolean turnoReasignado;
	private String ordenPagada;

	public Turno() {
	}

	public Turno(Doctor doctor, Estado estado, Persona persona,
			boolean turnoReasignado) {
		this.doctor = doctor;
		this.estado = estado;
		this.persona = persona;
		this.turnoReasignado = turnoReasignado;
	}

	public Turno(Doctor doctor, Estado estado, Persona persona, Date fecha,
			Date hora, boolean turnoReasignado, String ordenPagada) {
		this.doctor = doctor;
		this.estado = estado;
		this.persona = persona;
		this.fecha = fecha;
		this.hora = hora;
		this.turnoReasignado = turnoReasignado;
		this.ordenPagada = ordenPagada;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idturno", unique = true, nullable = false)
	public Integer getIdturno() {
		return this.idturno;
	}

	public void setIdturno(Integer idturno) {
		this.idturno = idturno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddoctor", nullable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpersona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "turno_reasignado", nullable = false)
	public boolean isTurnoReasignado() {
		return this.turnoReasignado;
	}

	public void setTurnoReasignado(boolean turnoReasignado) {
		this.turnoReasignado = turnoReasignado;
	}

	@Column(name = "orden_pagada", length = 45)
	public String getOrdenPagada() {
		return this.ordenPagada;
	}

	public void setOrdenPagada(String ordenPagada) {
		this.ordenPagada = ordenPagada;
	}

}
